apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:Shehats/cd-works.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: cd-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true