apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-app
spec:
  selector:
    matchLabels:
      app: cd-app
  replicas: 2
  template:
    metadata:
      labels:
        app: cd-app
    spec:
      containers:
      - name: cd-app
        image: sshehatatech/cd-app:1.0
        ports:
        - containerPort: 8080
